-- ===========================================================================
-- DIFF STRUCTURE : PRODUCTION contre REJEU DU DEPOT
-- ===========================================================================
--
-- La liste `rejeu` ci-dessous est l'inventaire, objet par objet, de la base
-- reconstruite a partir des fichiers du depot sur PostgreSQL 16, migrations 36
-- et 37 comprises. La requete la confronte a la production et ne rend que les
-- ecarts.
--
--   manque_en_prod    : le depot le cree, la production ne l'a pas.
--                       Soit un fichier n'a pas encore ete lance en production,
--                       soit l'objet y a ete supprime a la main.
--
--   absent_du_depot   : la production l'a, aucun fichier ne le cree.
--                       C'est un objet cree a la main dans le tableau de bord,
--                       donc perdu a la prochaine reconstruction.
--
-- Comparaison par nom, pas par definition : une difference de version de
-- PostgreSQL (16 ici, 17 en production) change le texte rendu par le
-- catalogue mais jamais les noms. Les fonctions fournies par une extension
-- sont exclues des deux cotes.
--
-- Zero ligne veut dire que le depot decrit exactement la production.
-- ===========================================================================

with rejeu(categorie, objet) as (values
  ('colonnes','absences.absent_date'),
  ('colonnes','absences.created_at'),
  ('colonnes','absences.id'),
  ('colonnes','absences.profile_id'),
  ('colonnes','absences.reason'),
  ('colonnes','absences.round_id'),
  ('colonnes','club_courts.available_from'),
  ('colonnes','club_courts.available_to'),
  ('colonnes','club_courts.club_id'),
  ('colonnes','club_courts.court_name'),
  ('colonnes','club_courts.created_at'),
  ('colonnes','club_courts.id'),
  ('colonnes','club_courts.sort_order'),
  ('colonnes','clubs.auto_renew_players'),
  ('colonnes','clubs.club_address'),
  ('colonnes','clubs.club_email'),
  ('colonnes','clubs.club_name'),
  ('colonnes','clubs.country'),
  ('colonnes','clubs.country_code'),
  ('colonnes','clubs.created_at'),
  ('colonnes','clubs.default_end_time'),
  ('colonnes','clubs.default_match_duration'),
  ('colonnes','clubs.default_max_players_per_group'),
  ('colonnes','clubs.default_min_players_per_group'),
  ('colonnes','clubs.default_number_of_courts'),
  ('colonnes','clubs.default_start_time'),
  ('colonnes','clubs.id'),
  ('colonnes','clubs.logo_url'),
  ('colonnes','clubs.open_to_visitors'),
  ('colonnes','clubs.region'),
  ('colonnes','clubs.updated_at'),
  ('colonnes','clubs.visitor_fee'),
  ('colonnes','elo_adjustments.applied_at'),
  ('colonnes','elo_adjustments.delta'),
  ('colonnes','elo_adjustments.id'),
  ('colonnes','elo_adjustments.profile_id'),
  ('colonnes','elo_adjustments.round_id'),
  ('colonnes','event_courts.available_from'),
  ('colonnes','event_courts.available_to'),
  ('colonnes','event_courts.court_name'),
  ('colonnes','event_courts.created_at'),
  ('colonnes','event_courts.id'),
  ('colonnes','event_courts.round_id'),
  ('colonnes','event_courts.sort_order'),
  ('colonnes','event_players.event_id'),
  ('colonnes','event_players.id'),
  ('colonnes','event_players.profile_id'),
  ('colonnes','event_players.registered_at'),
  ('colonnes','event_players.round_id'),
  ('colonnes','event_promotion_rules.created_at'),
  ('colonnes','event_promotion_rules.event_id'),
  ('colonnes','event_promotion_rules.id'),
  ('colonnes','event_promotion_rules.promoted_count'),
  ('colonnes','event_promotion_rules.relegated_count'),
  ('colonnes','event_promotion_rules.updated_at'),
  ('colonnes','event_rounds.created_at'),
  ('colonnes','event_rounds.deadline'),
  ('colonnes','event_rounds.end_date'),
  ('colonnes','event_rounds.end_time'),
  ('colonnes','event_rounds.estimated_match_duration'),
  ('colonnes','event_rounds.event_id'),
  ('colonnes','event_rounds.id'),
  ('colonnes','event_rounds.number_of_courts'),
  ('colonnes','event_rounds.playing_dates'),
  ('colonnes','event_rounds.round_number'),
  ('colonnes','event_rounds.start_date'),
  ('colonnes','event_rounds.start_time'),
  ('colonnes','event_rounds.status'),
  ('colonnes','event_rounds.updated_at'),
  ('colonnes','event_scoring_rules.created_at'),
  ('colonnes','event_scoring_rules.event_id'),
  ('colonnes','event_scoring_rules.id'),
  ('colonnes','event_scoring_rules.score_points'),
  ('colonnes','event_scoring_rules.updated_at'),
  ('colonnes','events.auto_renew'),
  ('colonnes','events.calendar_type'),
  ('colonnes','events.club_id'),
  ('colonnes','events.created_at'),
  ('colonnes','events.default_days_of_week'),
  ('colonnes','events.description'),
  ('colonnes','events.embed_token'),
  ('colonnes','events.event_name'),
  ('colonnes','events.exclude_public_holidays'),
  ('colonnes','events.id'),
  ('colonnes','events.invite_token'),
  ('colonnes','events.open_to_visitors'),
  ('colonnes','events.updated_at'),
  ('colonnes','group_players.created_at'),
  ('colonnes','group_players.group_id'),
  ('colonnes','group_players.id'),
  ('colonnes','group_players.profile_id'),
  ('colonnes','groups.created_at'),
  ('colonnes','groups.group_name'),
  ('colonnes','groups.id'),
  ('colonnes','groups.max_players'),
  ('colonnes','groups.round_id'),
  ('colonnes','matches.court_number'),
  ('colonnes','matches.created_at'),
  ('colonnes','matches.group_id'),
  ('colonnes','matches.id'),
  ('colonnes','matches.match_date'),
  ('colonnes','matches.match_time'),
  ('colonnes','matches.pending_at'),
  ('colonnes','matches.pending_by'),
  ('colonnes','matches.pending_score_p1'),
  ('colonnes','matches.pending_score_p2'),
  ('colonnes','matches.player1_id'),
  ('colonnes','matches.player2_id'),
  ('colonnes','matches.score'),
  ('colonnes','matches.updated_at'),
  ('colonnes','matches.winner_id'),
  ('colonnes','payments.amount'),
  ('colonnes','payments.created_at'),
  ('colonnes','payments.id'),
  ('colonnes','payments.paid_at'),
  ('colonnes','payments.profile_id'),
  ('colonnes','payments.round_id'),
  ('colonnes','payments.status'),
  ('colonnes','payments.updated_at'),
  ('colonnes','player_status.id'),
  ('colonnes','player_status.profile_id'),
  ('colonnes','player_status.status'),
  ('colonnes','player_status.updated_at'),
  ('colonnes','profile_sports.created_at'),
  ('colonnes','profile_sports.id'),
  ('colonnes','profile_sports.profile_id'),
  ('colonnes','profile_sports.sport_id'),
  ('colonnes','profiles.activation_token'),
  ('colonnes','profiles.address'),
  ('colonnes','profiles.avatar_url'),
  ('colonnes','profiles.club_id'),
  ('colonnes','profiles.created_at'),
  ('colonnes','profiles.email'),
  ('colonnes','profiles.first_name'),
  ('colonnes','profiles.id'),
  ('colonnes','profiles.is_linked'),
  ('colonnes','profiles.last_name'),
  ('colonnes','profiles.phone'),
  ('colonnes','profiles.power_ranking'),
  ('colonnes','profiles.role'),
  ('colonnes','profiles.updated_at'),
  ('colonnes','promotion_rules.club_id'),
  ('colonnes','promotion_rules.created_at'),
  ('colonnes','promotion_rules.id'),
  ('colonnes','promotion_rules.promoted_count'),
  ('colonnes','promotion_rules.relegated_count'),
  ('colonnes','promotion_rules.updated_at'),
  ('colonnes','schedule.arrival'),
  ('colonnes','schedule.created_at'),
  ('colonnes','schedule.departure'),
  ('colonnes','schedule.event_id'),
  ('colonnes','schedule.id'),
  ('colonnes','schedule.profile_id'),
  ('colonnes','scoring_rules.club_id'),
  ('colonnes','scoring_rules.created_at'),
  ('colonnes','scoring_rules.id'),
  ('colonnes','scoring_rules.score_points'),
  ('colonnes','scoring_rules.updated_at'),
  ('colonnes','sports.created_at'),
  ('colonnes','sports.id'),
  ('colonnes','sports.sport_name'),
  ('colonnes','visitor_requests.created_at'),
  ('colonnes','visitor_requests.event_id'),
  ('colonnes','visitor_requests.id'),
  ('colonnes','visitor_requests.message'),
  ('colonnes','visitor_requests.profile_id'),
  ('colonnes','visitor_requests.reviewed_at'),
  ('colonnes','visitor_requests.reviewed_by'),
  ('colonnes','visitor_requests.status'),
  ('colonnes','visitor_requests.updated_at'),
  ('contraintes','absences.absences_pkey'),
  ('contraintes','absences.absences_profile_id_fkey'),
  ('contraintes','absences.absences_profile_id_round_id_absent_date_key'),
  ('contraintes','absences.absences_round_id_fkey'),
  ('contraintes','club_courts.club_courts_club_id_fkey'),
  ('contraintes','club_courts.club_courts_pkey'),
  ('contraintes','clubs.clubs_pkey'),
  ('contraintes','elo_adjustments.elo_adjustments_pkey'),
  ('contraintes','elo_adjustments.elo_adjustments_profile_id_fkey'),
  ('contraintes','elo_adjustments.elo_adjustments_round_id_fkey'),
  ('contraintes','elo_adjustments.elo_adjustments_round_profile_key'),
  ('contraintes','event_courts.event_courts_pkey'),
  ('contraintes','event_courts.event_courts_round_id_fkey'),
  ('contraintes','event_players.event_players_event_id_fkey'),
  ('contraintes','event_players.event_players_event_profile_round_key'),
  ('contraintes','event_players.event_players_pkey'),
  ('contraintes','event_players.event_players_profile_id_fkey'),
  ('contraintes','event_players.event_players_round_id_fkey'),
  ('contraintes','event_promotion_rules.event_promotion_rules_event_id_fkey'),
  ('contraintes','event_promotion_rules.event_promotion_rules_event_id_key'),
  ('contraintes','event_promotion_rules.event_promotion_rules_pkey'),
  ('contraintes','event_promotion_rules.event_promotion_rules_promoted_count_check'),
  ('contraintes','event_promotion_rules.event_promotion_rules_relegated_count_check'),
  ('contraintes','event_rounds.event_rounds_event_id_fkey'),
  ('contraintes','event_rounds.event_rounds_event_id_round_number_key'),
  ('contraintes','event_rounds.event_rounds_pkey'),
  ('contraintes','event_rounds.event_rounds_status_check'),
  ('contraintes','event_scoring_rules.event_scoring_rules_event_id_fkey'),
  ('contraintes','event_scoring_rules.event_scoring_rules_event_id_key'),
  ('contraintes','event_scoring_rules.event_scoring_rules_pkey'),
  ('contraintes','events.events_calendar_type_check'),
  ('contraintes','events.events_club_id_fkey'),
  ('contraintes','events.events_event_name_key'),
  ('contraintes','events.events_pkey'),
  ('contraintes','group_players.group_players_group_id_fkey'),
  ('contraintes','group_players.group_players_group_id_profile_id_key'),
  ('contraintes','group_players.group_players_pkey'),
  ('contraintes','group_players.group_players_profile_id_fkey'),
  ('contraintes','groups.groups_pkey'),
  ('contraintes','groups.groups_round_id_fkey'),
  ('contraintes','matches.matches_group_id_fkey'),
  ('contraintes','matches.matches_pending_by_fkey'),
  ('contraintes','matches.matches_pkey'),
  ('contraintes','matches.matches_player1_id_fkey'),
  ('contraintes','matches.matches_player2_id_fkey'),
  ('contraintes','matches.matches_winner_id_fkey'),
  ('contraintes','payments.payments_pkey'),
  ('contraintes','payments.payments_profile_id_fkey'),
  ('contraintes','payments.payments_profile_id_round_id_key'),
  ('contraintes','payments.payments_round_id_fkey'),
  ('contraintes','player_status.player_status_pkey'),
  ('contraintes','player_status.player_status_profile_id_fkey'),
  ('contraintes','profile_sports.profile_sports_pkey'),
  ('contraintes','profile_sports.profile_sports_profile_id_fkey'),
  ('contraintes','profile_sports.profile_sports_profile_id_sport_id_key'),
  ('contraintes','profile_sports.profile_sports_sport_id_fkey'),
  ('contraintes','profiles.profiles_club_id_fkey'),
  ('contraintes','profiles.profiles_pkey'),
  ('contraintes','promotion_rules.promotion_rules_club_id_fkey'),
  ('contraintes','promotion_rules.promotion_rules_club_id_key'),
  ('contraintes','promotion_rules.promotion_rules_pkey'),
  ('contraintes','schedule.schedule_event_id_fkey'),
  ('contraintes','schedule.schedule_pkey'),
  ('contraintes','schedule.schedule_profile_id_fkey'),
  ('contraintes','scoring_rules.scoring_rules_club_id_fkey'),
  ('contraintes','scoring_rules.scoring_rules_club_id_key'),
  ('contraintes','scoring_rules.scoring_rules_pkey'),
  ('contraintes','sports.sports_pkey'),
  ('contraintes','sports.sports_sport_name_key'),
  ('contraintes','visitor_requests.visitor_requests_event_id_fkey'),
  ('contraintes','visitor_requests.visitor_requests_event_id_profile_id_key'),
  ('contraintes','visitor_requests.visitor_requests_pkey'),
  ('contraintes','visitor_requests.visitor_requests_profile_id_fkey'),
  ('contraintes','visitor_requests.visitor_requests_reviewed_by_fkey'),
  ('declencheurs','auth.users on_auth_user_created'),
  ('declencheurs','public.event_players trg_auto_visitor_payment'),
  ('declencheurs','public.event_players trg_event_players_delete'),
  ('declencheurs','public.event_players trg_event_players_insert'),
  ('declencheurs','public.event_players trg_visitor_payment_delete'),
  ('declencheurs','public.event_players trg_visitor_payment_insert'),
  ('declencheurs','public.event_rounds trg_cleanup_absences_on_event_complete'),
  ('declencheurs','public.matches trg_elo_on_match_result'),
  ('enums','payment_status_enum = paid,unpaid'),
  ('enums','player_status_enum = active,inactive,member,visitor,withdrawn,new,paid,unpaid'),
  ('enums','user_role = user,admin,superadmin'),
  ('enums','visitor_request_status = pending,approved,rejected,cancelled'),
  ('fonctions','apply_event_elo(uuid)'),
  ('fonctions','auto_copy_club_courts_to_event()'),
  ('fonctions','auto_create_visitor_payment()'),
  ('fonctions','auto_elo_on_event_complete()'),
  ('fonctions','cleanup_absences_on_event_complete()'),
  ('fonctions','create_new_round(uuid)'),
  ('fonctions','elo_apply_round(uuid)'),
  ('fonctions','elo_margin_multiplier(text)'),
  ('fonctions','elo_recompute_club(uuid)'),
  ('fonctions','elo_recompute_from_round(uuid)'),
  ('fonctions','elo_revert_round(uuid)'),
  ('fonctions','get_draws_by_embed_token(uuid,integer)'),
  ('fonctions','get_event_by_invite_token(uuid)'),
  ('fonctions','get_user_club_id()'),
  ('fonctions','handle_new_user()'),
  ('fonctions','is_admin()'),
  ('fonctions','is_superadmin()'),
  ('fonctions','remove_club_member(uuid)'),
  ('fonctions','request_visitor_registration(uuid,text)'),
  ('fonctions','review_visitor_request(uuid,text)'),
  ('fonctions','sync_active_on_event_register()'),
  ('fonctions','sync_inactive_on_event_unregister()'),
  ('fonctions','trg_elo_on_match_result()'),
  ('fonctions','trg_visitor_payment_on_registration()'),
  ('fonctions','trg_visitor_payment_on_unregistration()'),
  ('fonctions','update_event_statuses()'),
  ('fonctions','update_member_role(uuid,user_role)'),
  ('fonctions','upsert_player(uuid,text,text,text,text,integer,text,uuid,text[],time without time zone,time without time zone,uuid,uuid,date,numeric)'),
  ('indexes','absences_global_unique'),
  ('indexes','absences_pkey'),
  ('indexes','absences_profile_id_round_id_absent_date_key'),
  ('indexes','club_courts_pkey'),
  ('indexes','clubs_pkey'),
  ('indexes','elo_adjustments_pkey'),
  ('indexes','elo_adjustments_round_profile_key'),
  ('indexes','event_courts_pkey'),
  ('indexes','event_players_event_profile_round_key'),
  ('indexes','event_players_pkey'),
  ('indexes','event_promotion_rules_event_id_key'),
  ('indexes','event_promotion_rules_pkey'),
  ('indexes','event_rounds_event_id_round_number_key'),
  ('indexes','event_rounds_pkey'),
  ('indexes','event_scoring_rules_event_id_key'),
  ('indexes','event_scoring_rules_pkey'),
  ('indexes','events_event_name_key'),
  ('indexes','events_pkey'),
  ('indexes','group_players_group_id_profile_id_key'),
  ('indexes','group_players_pkey'),
  ('indexes','groups_pkey'),
  ('indexes','idx_absences_round_id'),
  ('indexes','idx_club_courts_club_id'),
  ('indexes','idx_elo_adjustments_profile_id'),
  ('indexes','idx_elo_adjustments_round_id'),
  ('indexes','idx_event_courts_round_id'),
  ('indexes','idx_event_players_event_id'),
  ('indexes','idx_event_players_profile_id'),
  ('indexes','idx_event_players_round_id'),
  ('indexes','idx_event_promotion_rules_event_id'),
  ('indexes','idx_event_rounds_event_id'),
  ('indexes','idx_event_rounds_status'),
  ('indexes','idx_event_scoring_rules_event_id'),
  ('indexes','idx_events_club_id'),
  ('indexes','idx_events_embed_token'),
  ('indexes','idx_events_invite_token'),
  ('indexes','idx_group_players_profile_id'),
  ('indexes','idx_groups_round_id'),
  ('indexes','idx_matches_group_id'),
  ('indexes','idx_matches_player1_id'),
  ('indexes','idx_matches_player2_id'),
  ('indexes','idx_payments_round_id'),
  ('indexes','idx_profile_sports_profile_id'),
  ('indexes','idx_profile_sports_sport_id'),
  ('indexes','idx_profiles_club_id'),
  ('indexes','idx_profiles_email'),
  ('indexes','idx_promotion_rules_club_id'),
  ('indexes','idx_schedule_event_id'),
  ('indexes','idx_schedule_profile_id'),
  ('indexes','idx_schedule_profile_no_event'),
  ('indexes','idx_scoring_rules_club_id'),
  ('indexes','idx_visitor_requests_event_id'),
  ('indexes','idx_visitor_requests_profile_id'),
  ('indexes','idx_visitor_requests_status'),
  ('indexes','matches_pkey'),
  ('indexes','payments_pkey'),
  ('indexes','payments_profile_id_round_id_key'),
  ('indexes','player_status_pkey'),
  ('indexes','profile_sports_pkey'),
  ('indexes','profile_sports_profile_id_sport_id_key'),
  ('indexes','profiles_pkey'),
  ('indexes','promotion_rules_club_id_key'),
  ('indexes','promotion_rules_pkey'),
  ('indexes','schedule_pkey'),
  ('indexes','scoring_rules_club_id_key'),
  ('indexes','scoring_rules_pkey'),
  ('indexes','sports_pkey'),
  ('indexes','sports_sport_name_key'),
  ('indexes','uniq_player_status_per_profile'),
  ('indexes','visitor_requests_event_id_profile_id_key'),
  ('indexes','visitor_requests_pkey'),
  ('policies','absences | Users and admins can delete club absences'),
  ('policies','absences | Users and admins can insert club absences'),
  ('policies','absences | Users can select club absences'),
  ('policies','club_courts | club_courts_delete'),
  ('policies','club_courts | club_courts_insert'),
  ('policies','club_courts | club_courts_select'),
  ('policies','club_courts | club_courts_update'),
  ('policies','clubs | Admins can update their own club'),
  ('policies','clubs | Everyone can select clubs'),
  ('policies','clubs | Superadmins can delete clubs'),
  ('policies','clubs | Superadmins can insert clubs'),
  ('policies','elo_adjustments | elo_adjustments_select'),
  ('policies','event_courts | Admins can delete club event courts'),
  ('policies','event_courts | Admins can insert club event courts'),
  ('policies','event_courts | Admins can update club event courts'),
  ('policies','event_courts | Users can select club event courts'),
  ('policies','event_players | Users can register to club events'),
  ('policies','event_players | Users can see club event registrations'),
  ('policies','event_players | Users can unregister from club events'),
  ('policies','event_promotion_rules | event_promotion_rules_delete'),
  ('policies','event_promotion_rules | event_promotion_rules_insert'),
  ('policies','event_promotion_rules | event_promotion_rules_select'),
  ('policies','event_promotion_rules | event_promotion_rules_update'),
  ('policies','event_rounds | Admins can delete club event rounds'),
  ('policies','event_rounds | Admins can insert club event rounds'),
  ('policies','event_rounds | Admins can update club event rounds'),
  ('policies','event_rounds | Users can select club event rounds'),
  ('policies','event_scoring_rules | event_scoring_rules_delete'),
  ('policies','event_scoring_rules | event_scoring_rules_insert'),
  ('policies','event_scoring_rules | event_scoring_rules_select'),
  ('policies','event_scoring_rules | event_scoring_rules_update'),
  ('policies','events | Admins can delete club events'),
  ('policies','events | Admins can insert club events'),
  ('policies','events | Admins can update club events'),
  ('policies','events | Users can select visible events'),
  ('policies','group_players | Admins can delete club group players'),
  ('policies','group_players | Admins can insert club group players'),
  ('policies','group_players | Users can see club group memberships'),
  ('policies','groups | Admins can delete club groups'),
  ('policies','groups | Admins can insert club groups'),
  ('policies','groups | Admins can update club groups'),
  ('policies','groups | Users can select their club groups'),
  ('policies','matches | Admins can delete club matches'),
  ('policies','matches | Admins can insert club matches'),
  ('policies','matches | Admins can update club matches'),
  ('policies','matches | Users can see club matches'),
  ('policies','payments | payments_delete'),
  ('policies','payments | payments_insert'),
  ('policies','payments | payments_select'),
  ('policies','payments | payments_update'),
  ('policies','player_status | Admins can delete club player statuses'),
  ('policies','player_status | Admins can insert club player statuses'),
  ('policies','player_status | Admins can update club player statuses'),
  ('policies','player_status | Users can view club player statuses'),
  ('policies','profile_sports | profile_sports_delete'),
  ('policies','profile_sports | profile_sports_insert'),
  ('policies','profile_sports | profile_sports_select'),
  ('policies','profiles | Admins can delete club profiles'),
  ('policies','profiles | profiles_insert'),
  ('policies','profiles | profiles_select'),
  ('policies','profiles | profiles_update'),
  ('policies','promotion_rules | Admins can insert club promotion rules'),
  ('policies','promotion_rules | Admins can update club promotion rules'),
  ('policies','promotion_rules | Users can select their club promotion rules'),
  ('policies','schedule | Admins can insert club schedules'),
  ('policies','schedule | Admins can update club schedules'),
  ('policies','schedule | Users and admins can delete club schedules'),
  ('policies','schedule | Users can select club schedules'),
  ('policies','scoring_rules | Admins can insert club scoring rules'),
  ('policies','scoring_rules | Admins can update club scoring rules'),
  ('policies','scoring_rules | Users can select their club scoring rules'),
  ('policies','sports | Everyone can select sports'),
  ('policies','sports | Superadmins can delete sports'),
  ('policies','sports | Superadmins can insert sports'),
  ('policies','sports | Superadmins can update sports'),
  ('policies','visitor_requests | Users can create visitor requests'),
  ('policies','visitor_requests | visitor_requests_select'),
  ('policies','visitor_requests | visitor_requests_update'),
  ('policies_storage','objects | Lecture publique des logos de club'),
  ('policies_storage','objects | Un admin depose le logo de son club'),
  ('policies_storage','objects | Un admin remplace le logo de son club'),
  ('policies_storage','objects | Un admin supprime le logo de son club')
),
prod as (
  select 'colonnes' as categorie, table_name||'.'||column_name as objet
    from information_schema.columns c
   where c.table_schema = 'public'
     and not exists (select 1 from pg_class k join pg_namespace kn on kn.oid = k.relnamespace
                      where kn.nspname = 'public' and k.relname = c.table_name
                        and k.relkind in ('v','m'))
  union all
  select 'contraintes', rel.relname||'.'||con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace n on n.oid = rel.relnamespace
   where n.nspname = 'public'
  union all
  select 'indexes', indexname from pg_indexes where schemaname = 'public'
  union all
  select 'fonctions', p.oid::regprocedure::text
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.prokind in ('f','p')
     and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
  union all
  select 'declencheurs', n.nspname||'.'||rel.relname||' '||tg.tgname
    from pg_trigger tg
    join pg_class rel on rel.oid = tg.tgrelid
    join pg_namespace n on n.oid = rel.relnamespace
   where not tg.tgisinternal and n.nspname in ('public','auth')
  union all
  select 'policies', tablename||' | '||policyname
    from pg_policies where schemaname = 'public'
  union all
  select 'policies_storage', tablename||' | '||policyname
    from pg_policies where schemaname = 'storage'
  union all
  select 'enums', t.typname||' = '||string_agg(e.enumlabel, ',' order by e.enumsortorder)
    from pg_type t
    join pg_enum e on e.enumtypid = t.oid
    join pg_namespace n on n.oid = t.typnamespace
   where n.nspname = 'public'
   group by t.typname
  union all
  select 'vues', c.relname
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind in ('v','m')
)
select coalesce(r.categorie, p.categorie) as categorie,
       case when p.objet is null then 'manque_en_prod' else 'absent_du_depot' end as ecart,
       coalesce(r.objet, p.objet) as objet
  from rejeu r
  full outer join prod p
    on p.categorie = r.categorie and p.objet = r.objet
 where r.objet is null or p.objet is null
 order by 1, 2, 3;
